language: erlang

otp_release:
  - 22.1
  - 21.3
  - 20.1
  - 19.3
  - 18.3

branches:
  only:
    - master

addons:
  postgresql: "9.3"

before_install:
  - wget https://s3.amazonaws.com/rebar3/rebar3
  - chmod +x rebar3

before_script:
  - psql -c 'create database pgpool_test;' -U postgres

script: "make travis"
